### ISSUE TITLE
Level command on character.

### ISSUE THREAD

**Issue by ramyalexis** [WCell/WCell#5]
When using lvl command on character for example 
# level 80 the character indeed got lvl 80 BUT no hp/mp scailing(as at start 100hp/100man this valuse persist throw lvl 80!) nor i can't open achivments tab (show min lvl requirements) nor gliph tab (also lvl requiremants)

**Comment by ramyalexis** [comment]
wow sorry for such font..
cant even imaging how it heppend..

**Comment by VillemP** [comment]
did you use #level or did you just use #set level 80

**Comment by ramyalexis** [comment]
i use #level 80 like describe in docs.

**Comment by Domiii** [comment]
The level command is fixed

**Comment by ramyalexis** [comment]
achivement still shows that it needs level more then ten but character is lvl 80...

**Comment by Domiii** [comment]
Please post it as a missing feature issue (Achievments are not implemented yet)
